services:
  - type: web
    name: velo-live-web
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: AUTH0_DOMAIN
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: TRANSPORT_EMAIL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: velo_community_db
          property: connectionString
    healthCheckPath: /
  - type: pserv
    name: velo_community_db
    env: docker
    region: oregon
    plan: free
    disk:
      name: velo-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1